Dev
FangfangFan/Interop-TestSuites pull request #14
Opened 2019-09-25 03:09 UTC by FangfangFan

Update MS-OXWSCORE capture code

2019-09-25 04:17 UTC, v-yahan reviewed
Please update according to the following comments:
1. Some RS are not updated: MS-OXWSCORE: R67, R69, R2302, R1256, R2315
                                               MS-OXWSCDATA: R1584, R1038
2. R23091 and R23093 are appeared twice in 2007, 2010, 2013, 2016 SHOULDMAY config files.
3. 
4. RS: Remove VerificationComment in R13411
5. RS: Verification should be "non-testable" in R108, R2045, R2047, R2051, R2061, R2064, R2065, R2066, R2067, R2068, R2069, R1087
6. R20451 and R20452 are verified twice. 
7. There is not capture code for R1351
8. R2923, R2932, R2935, R2936: no need to add "MS-OXWSCORE"
9. R2921, R2931, R20451: Please update the incorrect Req ID in comment
10. There are two blank line in R69, please remove one.

2019-09-25 07:30 UTC, XinwLi requested changes

2019-09-25 07:30 UTC, XinwLi commented on ExchangeWebServices/Source/MS-OXWSCORE/TestSuite/S02_ManageContactItems.cs
> +            Site.Assume.IsTrue(Common.IsRequirementEnabled(23091, this.Site), "[In Appendix C: Product Behavior] This element [MimeContent] is applicable for ContactType, TaskType and DistributionLis
refine the description to "The MimeContent element is not applicable for ContactType, TaskType and DistributionListType item when retrieving MIME content."

2019-09-25 07:30 UTC, XinwLi commented on ExchangeWebServices/Source/MS-OXWSCORE/TestSuite/S03_ManageDistributionListsItems.cs
> +            Site.Assume.IsTrue(Common.IsRequirementEnabled(23091, this.Site), "[In Appendix C: Product Behavior] This element [MimeContent] is applicable for ContactType, TaskType and DistributionLis
refine as above.

2019-09-27 05:43 UTC, v-yahan approved these changes

2019-09-27 05:59 UTC, v-yahan approved these changes

2019-09-27 08:30 UTC, XinwLi approved these changes

2019-09-29 03:48 UTC, merged