Add new cases for LockStatusSubResponseDataType and update RS.
FangfangFan/Interop-TestSuites pull request #71
Opened 2020-01-13 07:24 UTC by huangxiaochen1

2020-01-13 07:30 UTC, XinwLi requested changes

2020-01-13 07:30 UTC, XinwLi commented on .gitignore
> +/FileSyncandWOPI/Setup/Test Suite Client/SetupLogs/SharePointClientConfiguration.ps1.log
Please remove it

2020-01-13 07:30 UTC, XinwLi commented on FileSyncandWOPI/Source/SharedTestSuite/SharedAdapter/CaptureCode/FSSHTTP/MsfsshttpCommonCapture.cs
> +            // Verify MS-FSSHTTP requirement: MS-FSSHTTP_R2267
Add comment about why direct capture.

2020-01-16 03:19 UTC, XinwLi approved these changes

2020-01-17 05:59 UTC, FangfangFan approved these changes

2020-01-17 07:28 UTC, closed without merging